name: axeii_loader
description: "A simple loader utility for Axe-FX II"
publish_to: 'none'
version: 0.0.2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  window_manager: ^0.5.1
  file_picker: ^10.3.2
  flutter_midi_command_linux: ^0.3.0
  flutter_midi_command: ^0.5.1
  input_quantity: ^2.5.0
  flex_color_scheme: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


